name: Feature Request
description: Suggest a new feature or enhancement for the Marvel Quiz
title: "[Feature]: "
labels: ["enhancement", "feature-request"]
assignees:
  - octocat

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! 🚀

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: I also thought about...

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve experience
        - High - Critical for my use case
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What type of feature is this?
      options:
        - UI/UX Enhancement
        - New Question Type
        - Game Mechanics
        - Performance Improvement
        - Accessibility
        - Social Features
        - Analytics/Tracking
        - Other
    validations:
      required: true

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Examples
      description: If applicable, add mockups, wireframes, or examples from other apps
      placeholder: Drag and drop images here...

  - type: textarea
    id: impact
    attributes:
      label: User Impact
      description: How would this feature benefit users?
      placeholder: This would help users by...

  - type: dropdown
    id: willing-to-contribute
    attributes:
      label: Contribution
      description: Would you be willing to contribute to implementing this feature?
      options:
        - "Yes, I can submit a PR"
        - "Yes, I can help with design/testing"
        - "No, but I can provide feedback"
        - "Not sure"

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this isn't a duplicate
          required: true
        - label: This feature aligns with the project's goals and scope
          required: true
